import 'module';
import './foo';
import './foo/';
import './bar.js';
import './baz';
require('module');
require('./foo');
require('./foo/');
require('./bar.js');
require('./baz');
require(path);
fn('./foo');
